- name: ensure local path exists ({{ grafana_dashboards_local_path }}/mappings)
  become: no
  delegate_to: localhost
  file:
    path: "{{ grafana_dashboards_local_path }}/mappings"
    state: directory
    recurse: true

- grafana_dashboard_sync:
    path: "{{ grafana_dashboards_local_path }}"
    name: "{{ inventory_hostname }}"
    url: "{{ grafana_url }}"
    username: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
  register: result
  
- debug: var=result
